---
- name: Install prerequisites
  apt:  update_cache=yes
  loop: [ 'aptitude' ]

- name: Install Apache
  apt: name=apache2 update_cache=yes state=latest

- name: Start Apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Restart apache
  service:
    name: apache2
    state: restarted
