---
- name: Setup LAMP stack
  hosts: all
  remote_user: lamp
  become: yes

  roles:
    - Apache
    - Mysql
    - PHP

  handlers:
    - name: restart apache2
      systemd:
        name: apache2
        state: restarted
