---
  # Install MySQL
  - name: Install MySQL
    apt:
      name: mysql-server
      state: present

  # Start MySQL service
  - name: Start MySQL service
    service:
      name: mysql
      state: started
      enabled: yes


