---
  - name: Install PHP packages
    apt:
      name:
        - php
        - libapache2-mod-php
        - php-mysql
        - php-cli
      state: present

  - name: Replace file content with local file
    copy:
      src: config
      dest: /etc/apache2/mods-enabled/dir.conf

  - name: Create directory for your domain
    file:
      path: /var/www/lamp
      state: directory

  - name: Set ownership for your directory
    file:
      path: /var/www/lamp
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: Set permissions for /var/www/lamp
    file:
      path: /var/www/lamp
      state: directory
      mode: "0755"

  - name: Replace file content with local file
    copy:
      src: index.html
      dest: /var/www/lamp/index.html

  - name: Replace file content with local file
    copy:
      src: sites-available
      dest: /etc/apache2/sites-available/lamp.conf

  - name: Enable lamp site
    apache2_module:
      state: present
      name: rewrite
    notify:
      - restart apache2

  - name: Disable default site
    apache2_module:
      state: absent
      name: rewrite
    notify:
      - restart apache2

  - name: Replace file content with local file
    copy:
      src: info.php
      dest: /var/www/lamp/info.php
